### ISSUE TITLE
UI: Home page

### ISSUE THREAD

**Issue by SimonLab** [research-resource/research_resource#134]
linked to the [UI epic issue](https://github.com/research-resource/research_resource/issues/102#issuecomment-290390897)

![home_page_v1](https://cloud.githubusercontent.com/assets/6057298/24546939/630dce26-1605-11e7-9c7a-4ea8ca245b52.png)

elements still needed:
- [x] logo to add on the header
- [x] assets (images, other logos) see [this comment](https://github.com/research-resource/research_resource/issues/102#issuecomment-290427555) for the size of the images (could we get a set of different sizes?)
- [x] mobile view on the home page, how it will look, which elements do we want to display (images, menu, text,...) and how to get a nice mobile version of the home page?
- [x] Text content to be amended with the text from #127 
- [x] phone input to be replaced by password input. from #127: "just need to provide your name, email address and a password."
- [x] selected page to be bold in header

**Comment by indiamindwave24** [comment]
@SimonLab Apologies, your note in the UI epic got lost in my notifications somewhere!

'For the size of the assets it will depend on the resolution of the screen of the users. It will be great to have different size of the images, at least one for mobile (if the images are needed on mobile?) and one for desktop and maybe a medium size. This will allow us to load the right images for a specific device. I guess we need at least the biggest image width 2560px.'

-- if you are able to list the different sizes needed that would be ideal. I can provide as many as necessary but it would be great to be given specific sizes so I don't have to go back and change.

**Comment by indiamindwave24** [comment]
Please use this image as a placeholder 
![rr_placeholder_image](https://cloud.githubusercontent.com/assets/25007700/24705096/46ef2eaa-1a02-11e7-960f-a70a11c67833.jpg)

**Comment by SimonLab** [comment]
Thanks for the image @indiamindwave24 . At the moment I think we just need to get the paint swipe image, I'm not sure about all the different specific sizes we need yet but would it be possible to get one which match the width of the backgroud image (750px)? We can always reduce the size if we get a large image first. Thanks

**Comment by ellemindwave** [comment]
Have asked @indiamindwave24 and she is going to send over the paint splash and the logo. 
If you could also send over the logos for the footer that would be 👌  thanks!

**Comment by indiamindwave24** [comment]
![paint](https://cloud.githubusercontent.com/assets/25007700/24790914/131680e6-1b70-11e7-9b13-404df3678244.png)

**Comment by indiamindwave24** [comment]
This is the font for 'Welcome to'
[Lemon Tuesday.otf.zip](https://github.com/research-resource/research_resource/files/904898/Lemon.Tuesday.otf.zip)

As it only appears in this one place, I have also created it as an SVG - I don't know which is best
[RR_Welcome_to-01.svg.zip](https://github.com/research-resource/research_resource/files/904908/RR_Welcome_to-01.svg.zip)

Do let me know if there are any issues with this

**Comment by indiamindwave24** [comment]
@SimonLab Here is the logo — apologies for the delay

**Comment by indiamindwave24** [comment]
[RR_Logo.svg.zip](https://github.com/research-resource/research_resource/files/913487/RR_Logo.svg.zip)
Lol didn't attach

**Comment by indiamindwave24** [comment]
@Danwhy @SimonLab the Logo at the top of the page is very small. The text above and below the 'TTRR' should appear around the same size as the body text of the site.

**Comment by indiamindwave24** [comment]
@Danwhy @SimonLab What fonts are being used? The body text seems very bold and the title font is different to the provided visuals

**Comment by Danwhy** [comment]
@We're using Montreal for the body and Montreal Bold for the headers. The only adjustment we've made to the fonts you gave us is adding some letter spacing: 1px for the regular and 3px for bold.
